DROP TABLE IF EXISTS user_profile CASCADE;
CREATE TABLE user_profile (
  	user_profile_id SERIAL PRIMARY KEY,
  	first_name  varchar(50) NOT NULL,
  	last_name   varchar(50) NOT NULL,
	age smallint CHECK (age BETWEEN 18 AND 65),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	user_id integer REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO
	user_profile
	(first_name, last_name, age, user_id)
	VALUES
    ('Gerry',  'Dominichelli', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Wright', 'Davson', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Horst', 'Janz', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Athene', 'Alven', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Jo-anne', 'Burgisi', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Merwin', 'Snewin', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Sandro', 'Beetlestone', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Reinald', 'Wratten', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Sawyere', 'Joska', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Terencio', 'Trengove', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Ingar', 'Vossgen', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Dannye', 'Trenouth', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Elmira', 'Drane', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Marwin', 'Birchill', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Levin', 'Pidgen', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Emmeline', 'Maskell', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Wilton', 'Ivens', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Isidor', 'Dendle', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Tuckie', 'Bushby', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Emanuel', 'Henricsson', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Phyllis', 'Kynan', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Emera', 'Dafter', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Bondy', 'Hachard', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Merwyn', 'Cromley', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Elbert', 'Whetland', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Gerri', 'Foxley', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Courtnay', 'Hachette', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Eadith', 'Penkethman', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Tabitha', 'Dyter', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Darryl', 'Willerton', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Michail', 'Cregeen', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Veronica', 'Jonson', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Ebonee', 'Capnor', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Lionel', 'Napoli', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Jasen', 'Lobell', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Annecorinne', 'Vokes', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Abdul', 'Scimonelli', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Alwin', 'Skedge', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Garth', 'Bolstridge', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Gillian', 'Archibold', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Caroljean', 'Dorkin', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Tove', 'Juggins', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Lurette', 'Whitticks', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Pippy', 'Lambole', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Bendicty', 'Wattisham', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Mahmoud', 'Bakhrushin', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Lettie', 'Ely', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Gennifer', 'MacQueen', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Arnoldo', 'Gettens', rand_num_between(18, 65), rand_num_between(1, 50)),
    ('Hilliard', 'Throssell', rand_num_between(18, 65), rand_num_between(1, 50));

SELECT * FROM user_profile;
