
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    ID SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(64) NOT NULL CHECK (CHAR_LENGTH(password) BETWEEN 6 AND 64),
    active BOOLEAN DEFAULT true,
    verified BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT current_timestamp
);
INSERT INTO users
	(username, email, password, verified, created_at)
	VALUES
        ( 'easkin0', 'nmartins0@hostgator.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'cstate1', 'tgorbell1@zimbio.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'fdionsetti2', 'wkeller2@amazon.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'mbrentnall3', 'gattenborough3@homestead.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'nroddy4', 'kdocharty4@oakley.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'broden5', 'wmelchior5@statcounter.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'rnewnham6', 'dmundie6@joomla.org', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'tsiddaley7', 'niwanowski7@artisteer.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'ddimmock8', 'ctrase8@yellowpages.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'hmccarly9', 'csoppit9@wix.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'hashnessa', 'zjahna@smugmug.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'gradishb', 'kgreigb@netscape.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'rchetwindc', 'echitterc@globo.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'ncaffind', 'ganstyd@dyndns.org', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'wfosdicke', 'avaggerse@about.me', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'spyattf', 'esterrickerf@sogou.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'dchiecog', 'dcouchmang@forbes.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'kstruish', 'aespadah@upenn.edu', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'rboswardi', 'mjoddinsi@odnoklassniki.ru', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'bbarrasj', 'aeborallj@digg.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'bbennisk', 'docoskerryk@uiuc.edu', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'othompsonl', 'sgaroghanl@craigslist.org', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'alampingm', 'jplaydenm@taobao.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'jiacofon', 'pburgissn@cdc.gov', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'lchantero', 'fsandayo@unesco.org', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'hbrometp', 'achasep@mashable.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'bgregoriq', 'ddefrancescoq@chicagotribune.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'waldisr', 'klapworthr@infoseek.co.jp', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'ehalshos', 'kdulens@godaddy.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'ngoodburnt', 'csorsbiet@flavors.me', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'athrelfallu', 'gramu@bravesites.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'codyvoiev', 'ksollettv@tinyurl.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'sticknerw', 'hlegonw@archive.org', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'mmacgianyx', 'vnelx@blogger.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'cpethery', 'agerty@amazon.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'mdartz', 'jgerritzenz@ox.ac.uk', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'hricardon10', 'cfairleigh10@spotify.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'amccumskay11', 'mpahlsson11@bbb.org', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'mhearsum12', 'tscurrah12@ask.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'cwedgwood13', 'qorris13@yahoo.co.jp', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'mwhitton14', 'nwinterbottom14@flavors.me', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'dcuckson15', 'bgirone15@google.nl', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'leiler16', 'kphilps16@bloglines.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'qcrollman17', 'dhessel17@surveymonkey.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'khazelby18', 'dkeeley18@mashable.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'kvassano19', 'hodoohaine19@cpanel.net', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'cpounder1a', 'plorking1a@pinterest.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'broxbrough1b', 'doakinfold1b@zimbio.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'gfealey1c', 'ztallet1c@plala.or.jp', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) ),
        ( 'amacieja1d', 'rumpleby1d@hc360.com', '000000', RANDOM()::INT::BOOLEAN,
            (current_timestamp - (  trunc( random() * ( 365-1+1 ) + 1 )  || 'days')::interval) );
SELECT * FROM users;
