default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: job_tracker
    username: postgres
    password: Rails.application.credentials.dig(:POSTGRES, :password)
    host: localhost
    timeout: 5000

development:
    <<: *default

production:
    <<: *default
    password: <%= ENV["JOB_TRACKER_DATABASE_PASSWORD"] %>
# test:
#   <<: *default
#   database: job_tracker_test
